"""Isaac eval <-> local splat-render wiring (opt-in, fail-closed, truthfully labeled).

The render itself is monkeypatched so these stay hermetic/fast; the real render is
covered by the splat_scene_render integration path.
"""
from __future__ import annotations

import json
from pathlib import Path

import blueprint_pipeline.splat_scene_render as ssr
from blueprint_pipeline.isaac_g1_site_3dgs_realistic_eval import (
    run_isaac_g1_site_3dgs_realistic_eval,
)

_CAM_IDS = ["head_pov", "torso", "wrist", "third_person", "overhead", "task_focus"]
FAKE_COMPLETED = {
    "schema_version": "splat_scene_render.v1",
    "status": "completed",
    "rendered_by": "reference_spark_renderer",
    "nonblank_camera_count": 6,
    "cameras": [
        {"id": cid, "path": f"/tmp/frames/{cid}.png", "bytes": 500000, "nonblank": True}
        for cid in _CAM_IDS
    ],
    "scene_geometry": {"up_axis": 2, "center": [0.0, 0.0, 0.0]},
    "robot_start_pose": {"position": [1.0, 2.0, 0.0], "facing_yaw_deg": 45.0},
    "mp4": {"status": "completed", "mp4": "/tmp/frames/scene_render.mp4"},
    "blockers": [],
    "proof_boundary": {"captured_scene_displayed": True, "rendered_by_isaac_rtx": False},
}


def _write_gaussian_ply(path: Path) -> None:
    path.write_text(
        "\n".join(
            [
                "ply", "format ascii 1.0", "comment Generated by splat-transform",
                "element vertex 2",
                "property float x", "property float y", "property float z",
                "property float scale_0", "property float rot_0", "property float opacity",
                "end_header", "0 0 0 1 0 1", "1 0 0 1 0 1",
            ]
        )
        + "\n",
        encoding="utf-8",
    )


def _setup(tmp_path: Path):
    ply = tmp_path / "scene.ply"
    spz = tmp_path / "scene.spz"
    _write_gaussian_ply(ply)
    spz.write_bytes(b"SPZ\x00placeholder")
    return ply, spz


def _run(tmp_path: Path, job_id: str, *, render_splat_views: bool):
    ply, spz = _setup(tmp_path)
    result = run_isaac_g1_site_3dgs_realistic_eval(
        ply_asset=ply,
        spz_asset=spz,
        job_id=job_id,
        job_root=tmp_path / "robot_eval_jobs",
        task_limit=1,
        spawn_limit=1,
        render_splat_views=render_splat_views,
        generated_at="2026-06-20T00:00:00+00:00",
    )
    return Path(result["job_dir"])


def test_eval_wires_completed_reference_render(tmp_path, monkeypatch) -> None:
    monkeypatch.setattr(ssr, "render_splat_scene", lambda *a, **k: dict(FAKE_COMPLETED))
    job_dir = _run(tmp_path, "isaac-splat-wire", render_splat_views=True)

    svr = json.loads((job_dir / "splat_visual_render_manifest.json").read_text())
    assert svr["realistic_splat_visual_rendered"] is True
    assert svr["status"] == "completed_reference_render"
    assert svr["rendered_by"] == "reference_spark_renderer"
    assert svr["rendered_by_isaac_rtx"] is False
    assert svr["nonblank_camera_count"] == 6
    assert svr["robot_start_pose"]["position"] == [1.0, 2.0, 0.0]

    cam = json.loads((job_dir / "camera_manifest.json").read_text())
    assert cam["camera_evidence_status"] == "rendered_by_reference_spark_renderer_isaac_rtx_pending"
    assert cam["reference_splat_render"]["rendered_by_isaac_rtx"] is False
    assert cam["reference_splat_render"]["nonblank_camera_count"] == 6

    vtb = json.loads((job_dir / "visual_truth_boundary.json").read_text())
    assert vtb["realistic_splat_visual_rendered"] is True
    assert vtb["realistic_splat_visual_rendered_by_isaac_rtx"] is False

    assert (job_dir / "splat_scene_render" / "manifest.json").is_file()


def test_eval_default_off_keeps_blocked_placeholder(tmp_path) -> None:
    job_dir = _run(tmp_path, "isaac-splat-off", render_splat_views=False)
    svr = json.loads((job_dir / "splat_visual_render_manifest.json").read_text())
    assert svr["status"] == "blocked"
    assert svr["realistic_splat_visual_rendered"] is False
    assert "splat_renderer_or_isaac_composite_runtime_not_executed" in svr["blockers"]
    vtb = json.loads((job_dir / "visual_truth_boundary.json").read_text())
    assert vtb["realistic_splat_visual_rendered"] is False
    cam = json.loads((job_dir / "camera_manifest.json").read_text())
    assert cam["camera_evidence_status"] == "blocked_until_isaac_or_splat_renderer_runs"


def test_eval_render_blocked_stays_honest(tmp_path, monkeypatch) -> None:
    monkeypatch.setattr(
        ssr,
        "render_splat_scene",
        lambda *a, **k: {
            "schema_version": "splat_scene_render.v1",
            "status": "blocked",
            "rendered_by": "reference_spark_renderer",
            "blockers": ["render_harness_unavailable"],
            "proof_boundary": {"captured_scene_displayed": False, "rendered_by_isaac_rtx": False},
        },
    )
    job_dir = _run(tmp_path, "isaac-splat-blocked", render_splat_views=True)
    svr = json.loads((job_dir / "splat_visual_render_manifest.json").read_text())
    assert svr["status"] == "blocked"
    assert svr["realistic_splat_visual_rendered"] is False
    vtb = json.loads((job_dir / "visual_truth_boundary.json").read_text())
    assert vtb["realistic_splat_visual_rendered"] is False
