"""CPU replay of the exact PhysX 110.1.13 defaults installed during V23.

USD caches discovered schemas for the interpreter lifetime. Each case uses a
fresh CPU interpreter so the codeless fixture cannot alter another test's USD
registry, or depend on collection order. No Isaac or PhysX runtime is loaded.
"""
from __future__ import annotations

import json
from pathlib import Path
import subprocess
import sys

import pytest


# Exact scalar declarations from generatedSchema.usda, sha256
# 4a7638c3890522bbe7c25600c0090e6cb7f403550ccb8be7641bf84034213b83.
_SCHEMA = '''#usda 1.0
class "PhysxSceneAPI"
{
    float physxScene:maxBiasCoefficient = inf
}
class "PhysxCollisionAPI"
{
    float physxCollision:contactOffset = -inf
    float physxCollision:restOffset = -inf
}
'''


def _exercise_exact_schema(root: Path, case: str) -> None:
    from pxr import Plug, Sdf, Usd
    from blueprint_pipeline import policy_scientific_reset as reset
    from tests.test_native_usd_reset_serialization import _native_usd_fixture

    schema_names = ("PhysxSceneAPI", "PhysxCollisionAPI")
    types = {"PhysxSchema" + name: {
        "alias": {"UsdSchemaBase": name}, "autoGenerated": True,
        "bases": ["UsdAPISchemaBase"], "schemaIdentifier": name, "schemaKind": "singleApplyAPI",
    } for name in schema_names}
    (root / "plugInfo.json").write_text(json.dumps({"Plugins": [{
        "Type": "resource", "Name": "blueprintTestPhysxResetSchema", "Root": ".",
        "ResourcePath": ".", "Info": {"Types": types},
    }]}))
    (root / "generatedSchema.usda").write_text(_SCHEMA.replace("float ", "double ") if case == "wrong_type" else _SCHEMA)
    assert Plug.Registry().RegisterPlugins(str(root))
    with pytest.MonkeyPatch.context() as monkeypatch:
        fixture = _native_usd_fixture(monkeypatch)
        stage = fixture.stage
        physics = stage.GetPrimAtPath("/World/physics")
        collider = stage.GetPrimAtPath("/World/envs/env_0/task_object")
        assert physics.ApplyAPI("PhysxSceneAPI")
        assert collider.ApplyAPI("PhysxCollisionAPI")
        attributes = [(physics.GetAttribute("physxScene:maxBiasCoefficient"), float("inf")),
            (collider.GetAttribute("physxCollision:contactOffset"), -float("inf")),
            (collider.GetAttribute("physxCollision:restOffset"), -float("inf"))]
        for attribute, sentinel in attributes:
            assert attribute.Get() == sentinel
            assert str(attribute.GetTypeName()) == ("double" if case == "wrong_type" else "float")
            assert attribute.GetResolveInfo().GetSource() == Usd.ResolveInfoSourceFallback

        def read(candidate="pi05_droid"):
            return reset.seal_reset_readback(binding={"candidate_id": candidate,
                "cell_id": "anchor", "seed": 31, "task_spec_digest": "sha256:" + "1" * 64,
                "resolved_scenario_digest": "sha256:" + "2" * 64},
                **reset.read_native_reset_channels(fixture.built, fixture.episode))

        if case == "wrong_type":
            for attribute, _sentinel in attributes:
                with pytest.raises(ValueError):
                    reset._native_usd_attribute(attribute)
            failed = read()
            assert not failed["complete"] and {"physics:ValueError", "colliders:ValueError"} <= set(failed["gaps"])
            assert any("usd_type=double" in gap for gap in failed["gaps"])
            print("cpu_physx_schema_case_passed:" + case)
            return
        baseline = read()
        assert baseline["complete"] is True, baseline["gaps"]
        assert reset.compare_reset_readbacks(baseline, read("groot_n17_droid"))["status"] == "matched"
        if case in {"fallback", "authored"}:
            for attribute, sentinel in attributes:
                if case == "authored":
                    attribute.Set(sentinel)
                value = reset._native_usd_attribute(attribute)
                assert value["source"] == ("usd_schema_fallback" if case == "fallback" else "usd_authored_configuration")
                assert value["value_tokens"] == ["inf" if sentinel > 0 else "-inf"]
                assert value["measured_numeric_value"] is False
                assert value["usd_type"] == "float" and value["configuration_semantics"]
            assert read()["complete"] is True
        elif case in {"changed_source", "changed_finite"}:
            attribute, sentinel = attributes[0]
            attribute.Set(sentinel if case == "changed_source" else 1000.0)
            if case == "changed_finite":
                assert reset._native_usd_attribute(attribute) == 1000.0
            comparison = reset.compare_reset_readbacks(baseline, read("groot_n17_droid"))
            assert comparison["status"] == "mismatch" and comparison["comparison_eligible"] is False
            assert any("physxScene:maxBiasCoefficient" in path for path in comparison["mismatches"])
        elif case in {"opposite_sign", "nan", "missing_api"}:
            for attribute, sentinel in attributes:
                if case == "missing_api":
                    prim = stage.DefinePrim("/World/not_a_physx_configuration")
                    attribute = prim.CreateAttribute(attribute.GetName(), Sdf.ValueTypeNames.Float)
                attribute.Set(-sentinel if case == "opposite_sign" else float("nan") if case == "nan" else sentinel)
                with pytest.raises(ValueError):
                    reset._native_usd_attribute(attribute)
        elif case == "unknown_setting":
            unknown = physics.CreateAttribute("physxScene:unrecognizedLimit", Sdf.ValueTypeNames.Float)
            unknown.Set(float("inf"))
            with pytest.raises(ValueError):
                reset._native_usd_attribute(unknown)
            failed = read()
            assert not failed["complete"] and "physics:ValueError" in failed["gaps"]
            assert any("/World/physics.physxScene:unrecognizedLimit" in gap for gap in failed["gaps"])
            assert reset.compare_reset_readbacks(failed, failed)["status"] == "unverified"
        elif case == "numeric_measurement":
            fixture.built.env.unwrapped.scene["robot"].data.joint_pos[0, 0] = float("inf")
            failed = read()
            assert not failed["complete"] and "robot:ValueError" in failed["gaps"]
            with pytest.raises(ValueError):
                reset._native(float("inf"))
        elif case == "gap_diagnostics":
            attribute = physics.CreateAttribute("physics:unreadableConfiguration", Sdf.ValueTypeNames.String)
            attribute.Set("configured")
            private_value = "private_value_must_not_be_retained"

            class UnreadableValue:
                def tolist(self):
                    raise ValueError(private_value)

            class AttributeEdge:
                def Get(self):
                    return UnreadableValue()
                def __getattr__(self, name):
                    return getattr(attribute, name)

            original = reset._native_usd_attribute
            monkeypatch.setattr(reset, "_native_usd_attribute", lambda value:
                original(AttributeEdge() if value.GetPath() == attribute.GetPath() else value))
            failed = read()
            assert not failed["complete"] and "physics:ValueError" in failed["gaps"]
            assert any("/World/physics.physics:unreadableConfiguration:usd_type=string:"
                "source=Usd.ResolveInfoSourceDefault:error=ValueError" in gap for gap in failed["gaps"])
            assert private_value not in json.dumps(failed)
        else:
            raise AssertionError(case)
    print("cpu_physx_schema_case_passed:" + case)


@pytest.mark.slow
@pytest.mark.parametrize("case", ["fallback", "authored", "changed_source", "changed_finite",
    "opposite_sign", "nan", "wrong_type", "missing_api", "unknown_setting", "numeric_measurement", "gap_diagnostics"])
def test_exact_physx_schema_cpu_regression(tmp_path, case):
    repo = Path(__file__).resolve().parents[1]
    program = """import sys
from pathlib import Path
repo = Path(sys.argv[1])
sys.path[:0] = [str(repo / 'src'), str(repo)]
from tests.test_native_physx_reset_serialization import _exercise_exact_schema
_exercise_exact_schema(Path(sys.argv[2]), sys.argv[3])
"""
    result = subprocess.run([sys.executable, "-I", "-B", "-c", program, str(repo), str(tmp_path), case],
        capture_output=True, text=True, timeout=30)
    assert result.returncode == 0, result.stdout + result.stderr
    assert "cpu_physx_schema_case_passed:" + case in result.stdout
