from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path
from types import ModuleType, SimpleNamespace
import xml.etree.ElementTree as ET

import numpy as np
import pytest
from PIL import Image

from blueprint_pipeline import g1_site_3dgs_mujoco_preview as preview
from blueprint_pipeline.g1_site_3dgs_mujoco_preview import (
    _attempt_visual_asset_mesh_conversion,
    _default_scene_proxies,
    _write_proxy_scene_obj,
    build_default_spawns,
    build_default_tasks,
    build_scenario_eval_matrix,
    inspect_scene_asset,
    inspect_optional_scene_metadata,
    validate_spawns,
)


def test_gaussian_ply_without_faces_blocks_direct_obj_conversion(tmp_path: Path) -> None:
    ply = tmp_path / "gaussian.ply"
    ply.write_text(
        "\n".join(
            [
                "ply",
                "format ascii 1.0",
                "comment Generated by splat-transform",
                "element vertex 2",
                "property float x",
                "property float y",
                "property float z",
                "property float scale_0",
                "property float rot_0",
                "property float opacity",
                "end_header",
                "0 0 0 1 0 1",
                "1 0 0 1 0 1",
            ]
        )
        + "\n",
        encoding="utf-8",
    )
    spz = tmp_path / "scene.spz"
    spz.write_bytes(b"\x1f\x8bplaceholder")

    ply_inspection = inspect_scene_asset(ply)
    spz_inspection = inspect_scene_asset(spz)
    attempts = _attempt_visual_asset_mesh_conversion(
        ply_asset=ply,
        spz_asset=spz,
        output_dir=tmp_path / "conversion",
        ply_inspection=ply_inspection,
        spz_inspection=spz_inspection,
    )

    assert ply_inspection["asset_kind"] == "gaussian_ply"
    assert ply_inspection["ply_header"]["has_face_element"] is False
    assert attempts[0]["status"] == "blocked"
    assert attempts[0]["blocker"] == "source_ply_has_no_triangle_faces"
    assert any(attempt["target_format"] == "msh" and attempt["status"] == "blocked" for attempt in attempts)


def test_proxy_obj_and_matrix_preserve_invalid_spawns(tmp_path: Path) -> None:
    proxies = _default_scene_proxies()
    proxy_obj = _write_proxy_scene_obj(tmp_path / "generated_classroom_proxy.obj", proxies)
    spawns = build_default_spawns()
    tasks = build_default_tasks()
    spawn_manifest = validate_spawns(
        spawns=spawns,
        proxies=proxies,
        generated_at="2026-06-20T00:00:00+00:00",
    )
    matrix = build_scenario_eval_matrix(
        job_id="job-test",
        tasks=tasks,
        spawns=spawn_manifest["spawns"],
        camera_ids=["pov", "third_person", "overhead", "task_focus"],
        generated_at="2026-06-20T00:00:00+00:00",
    )

    assert proxy_obj["status"] == "completed"
    assert proxy_obj["face_count"] > 0
    assert Path(proxy_obj["path"]).is_file()
    assert spawn_manifest["spawn_count"] == 5
    assert spawn_manifest["invalid_spawn_count"] >= 1
    assert matrix["scenario_eval_run_count"] == len(tasks) * len(spawns)
    assert any(
        run["spawn_id"] == "blocked_occluded_route_variant"
        for run in matrix["runs"]
    )
    assert all("deterministic_seed" in run for run in matrix["runs"])


def test_optional_scene_metadata_inspection_records_counts(tmp_path: Path) -> None:
    labels = tmp_path / "labels.json"
    labels.write_text(
        '{"objects": [{"id": "desk"}, {"id": "chalkboard"}], "rooms": [{"id": "classroom"}]}',
        encoding="utf-8",
    )

    result = inspect_optional_scene_metadata(labels, metadata_kind="labels_json")

    assert result["status"] == "inspected"
    assert result["metadata_kind"] == "labels_json"
    assert result["objects_count"] == 2
    assert result["rooms_count"] == 1


def test_scene_asset_metadata_conversion_and_proxy_helpers(monkeypatch, tmp_path: Path) -> None:
    assert preview._repo_root().name == "BlueprintCapturePipeline"
    missing = inspect_scene_asset(tmp_path / "missing.ply")
    assert missing["status"] == "missing"
    txt = tmp_path / "notes.txt"
    txt.write_text("hello", encoding="utf-8")
    assert inspect_scene_asset(txt)["asset_kind"] == "txt"

    bad_ply = tmp_path / "bad.ply"
    bad_ply.write_text("ply\nformat ascii 1.0\n", encoding="utf-8")
    assert preview._read_ply_header(bad_ply)["blocker"] == "ply_header_end_not_found"

    assert inspect_optional_scene_metadata(None, metadata_kind="labels")["status"] == "not_provided"
    assert inspect_optional_scene_metadata(tmp_path / "absent.json", metadata_kind="labels")["status"] == "missing"
    labels_array = tmp_path / "labels-array.json"
    labels_array.write_text(json.dumps([{"label": "chair"}, {"label": "chair"}, {"label": "table"}]), encoding="utf-8")
    assert inspect_optional_scene_metadata(labels_array, metadata_kind="labels")["label_counts"]["chair"] == 2
    scalar_json = tmp_path / "scalar.json"
    scalar_json.write_text('"value"', encoding="utf-8")
    assert inspect_optional_scene_metadata(scalar_json, metadata_kind="scalar")["json_top_level_type"] == "str"
    invalid_json = tmp_path / "invalid.json"
    invalid_json.write_text("{", encoding="utf-8")
    assert inspect_optional_scene_metadata(invalid_json, metadata_kind="invalid")["status"] == "blocked"
    image_path = tmp_path / "occupancy.png"
    Image.fromarray(np.zeros((3, 4, 3), dtype=np.uint8)).save(image_path)
    image_metadata = inspect_optional_scene_metadata(image_path, metadata_kind="occupancy")
    assert image_metadata["image_width"] == 4
    corrupt_image = tmp_path / "corrupt.png"
    corrupt_image.write_bytes(b"not an image")
    assert inspect_optional_scene_metadata(corrupt_image, metadata_kind="corrupt")["status"] == "blocked"
    weird = tmp_path / "metadata.csv"
    weird.write_text("a,b", encoding="utf-8")
    assert "metadata_format_not_used_by_current_proxy_generator" in inspect_optional_scene_metadata(weird, metadata_kind="csv")["blockers"]

    mesh_ply = tmp_path / "mesh.ply"
    mesh_ply.write_text(
        "\n".join(
            [
                "ply",
                "format ascii 1.0",
                "element vertex 3",
                "property float x",
                "property float y",
                "property float z",
                "element face 1",
                "property list uchar int vertex_indices",
                "end_header",
                "0 0 0",
                "1 0 0",
                "0 1 0",
                "3 0 1 2",
            ]
        )
        + "\n",
        encoding="utf-8",
    )
    spz = tmp_path / "visual.spz"
    spz.write_bytes(b"SPZ")

    class FaceRows(list):
        @property
        def size(self) -> int:
            return len(self)

    class Mesh:
        faces = FaceRows([(0, 1, 2)])
        vertices = [(0, 0, 0), (1, 0, 0), (0, 1, 0)]

        def export(self, target: str) -> None:
            Path(target).write_text("o mesh\n", encoding="utf-8")

    trimesh_mod = ModuleType("trimesh")
    trimesh_mod.load = lambda *_args, **_kwargs: Mesh()
    monkeypatch.setitem(sys.modules, "trimesh", trimesh_mod)
    mesh_inspection = inspect_scene_asset(mesh_ply)
    conversion = _attempt_visual_asset_mesh_conversion(
        ply_asset=mesh_ply,
        spz_asset=spz,
        output_dir=tmp_path / "conversion-success",
        ply_inspection=mesh_inspection,
        spz_inspection=inspect_scene_asset(spz),
    )
    assert conversion[0]["status"] == "completed"

    class EmptyMesh(Mesh):
        faces = FaceRows()

    trimesh_mod.load = lambda *_args, **_kwargs: EmptyMesh()
    failed_conversion = _attempt_visual_asset_mesh_conversion(
        ply_asset=mesh_ply,
        spz_asset=spz,
        output_dir=tmp_path / "conversion-failed",
        ply_inspection=mesh_inspection,
        spz_inspection=inspect_scene_asset(spz),
    )
    assert failed_conversion[0]["blocker"] == "ply_mesh_to_obj_conversion_failed"
    missing_conversion = _attempt_visual_asset_mesh_conversion(
        ply_asset=tmp_path / "missing-source.ply",
        spz_asset=spz,
        output_dir=tmp_path / "conversion-missing",
        ply_inspection={},
        spz_inspection={},
    )
    assert missing_conversion[0]["blocker"] == "source_ply_missing"

    class FakeMjModel:
        @staticmethod
        def from_xml_path(path: str):
            if "obj_cube" in path:
                return SimpleNamespace(nmesh=1)
            raise RuntimeError("unsupported mesh")

    mujoco_mod = ModuleType("mujoco")
    mujoco_mod.__version__ = "fake"
    mujoco_mod.__file__ = "fake-mujoco.py"
    mujoco_mod.MjModel = FakeMjModel
    monkeypatch.setitem(sys.modules, "mujoco", mujoco_mod)
    probe = preview._probe_mujoco_mesh_support(tmp_path / "probe")
    assert probe["status"] == "completed"
    assert probe["probe_results"]["obj_cube"]["loaded"] is True
    assert probe["probe_results"]["ply_triangle"]["loaded"] is False

    occupancy = tmp_path / "occupancy.json"
    occupancy.write_text(json.dumps({"lower": [0, 0, 0], "upper": [8, 10, 3], "scale": 0.05}), encoding="utf-8")
    structure = tmp_path / "structure.json"
    structure.write_text(
        json.dumps(
            {
                "walls": [
                    {"location": [[0, 0], [0, 10]], "height": 3.0, "thickness": 0.2},
                    {"location": [[0, 10], [8, 10]], "height": 3.0, "thickness": 0.2},
                    {"location": "bad"},
                ],
                "holes": [{}],
            }
        ),
        encoding="utf-8",
    )
    labels = tmp_path / "labels.json"
    labels.write_text(
        json.dumps(
            [
                {
                    "ins_id": "1",
                    "label": "table",
                    "bounding_box": [{"x": 2, "y": 2, "z": 0}, {"x": 3, "y": 3, "z": 1}],
                },
                {
                    "ins_id": "2",
                    "label": "chair",
                    "bounding_box": [{"x": 4, "y": 4, "z": 0}, {"x": 4.8, "y": 4.8, "z": 1}],
                },
                {
                    "ins_id": "3",
                    "label": "shelf",
                    "bounding_box": [{"x": 6, "y": 2, "z": 0}, {"x": 7, "y": 4, "z": 2}],
                },
                {
                    "ins_id": "4",
                    "label": "wall lamp",
                    "bounding_box": [{"x": 1, "y": 1, "z": 1}, {"x": 1.2, "y": 1.2, "z": 2}],
                },
                {"ins_id": "bad", "label": "bad", "bounding_box": [{"x": "no"}]},
            ]
        ),
        encoding="utf-8",
    )
    proxies, manifest, anchors = preview.build_scene_proxies_from_metadata(
        labels_json=labels,
        structure_json=structure,
        occupancy_json=occupancy,
        max_label_proxies=10,
    )
    assert manifest["status"] == "completed"
    assert anchors["table_proxy_id"]
    assert any(proxy["source"] == "interiorgs_structure_json" for proxy in proxies)
    assert preview._load_json_mapping(None) == {}
    assert preview._load_json_mapping(tmp_path / "missing.json") == {}
    non_mapping = tmp_path / "non-mapping.json"
    non_mapping.write_text("[]", encoding="utf-8")
    assert preview._load_json_mapping(non_mapping) == {}
    assert preview._load_json_list(None) == []
    assert preview._load_json_list(tmp_path / "missing-list.json") == []
    mapping_json = tmp_path / "mapping.json"
    mapping_json.write_text('{"a": 1}', encoding="utf-8")
    assert preview._load_json_list(mapping_json) == []
    assert preview._load_json_list(non_mapping) == []
    assert preview._metadata_origin({"lower": "bad", "upper": [1, 2]})[2]["source"] == "missing_occupancy_bounds"
    assert preview._bbox_bounds({"bounding_box": []}) is None
    assert preview._bbox_bounds({"bounding_box": ["bad", {"x": 1, "y": 1}]}) is not None
    assert preview._proxy_from_label_item(
        {"ins_id": "flat", "label": "table", "bounding_box": [{"x": 1, "y": 1, "z": 1}, {"x": 1, "y": 2, "z": 2}]},
        origin_x=0,
        origin_y=0,
    ) is None
    assert preview._wall_proxy_from_segment({"location": [[0, 0], "bad"]}, index=1, origin_x=0, origin_y=0) is None
    assert preview._proxy_by_label([], "table") is None
    assert preview._label_proxy_color("potted plant") == [0.10, 0.45, 0.20, 1.0]
    assert preview._label_is_collision_candidate("floor lamp") is False

    anchored_spawns = build_default_spawns(anchors=anchors)
    anchored_tasks = build_default_tasks(anchors=anchors)
    matrix = build_scenario_eval_matrix(
        job_id="job",
        tasks=anchored_tasks[:1],
        spawns=anchored_spawns[:1],
        camera_ids=["pov"],
        generated_at="2026-06-20T00:00:00+00:00",
        route_planner_proxies=proxies,
    )
    assert matrix["runs"][0]["route_waypoints"]
    validation_edges = validate_spawns(
        spawns=[
            {"spawn_id": "high", "pose_xyz_yaw": [0, 0, 2.0, 0]},
            {"spawn_id": "expected", "pose_xyz_yaw": [0, 0, 0.8, 0], "expected_invalid_reason": "custom_expected_blocker"},
        ],
        proxies=[],
        generated_at="2026-06-20T00:00:00+00:00",
    )
    assert "spawn_floor_contact_not_in_expected_height_band" in validation_edges["spawns"][0]["blockers"]
    assert "custom_expected_blocker" in validation_edges["spawns"][1]["blockers"]
    _, limited_manifest, _ = preview.build_scene_proxies_from_metadata(
        labels_json=labels,
        structure_json=structure,
        occupancy_json=occupancy,
        max_label_proxies=1,
    )
    assert limited_manifest["selected_label_proxy_count"] == 1
    empty_obj = _write_proxy_scene_obj(
        tmp_path / "empty.obj",
        [{"proxy_id": "bad", "geom_type": "capsule"}, {"proxy_id": "short", "pos": [0], "size": [1]}],
    )
    assert empty_obj["status"] == "blocked"


def test_route_render_artifact_and_runner_edges(monkeypatch, capsys, tmp_path: Path) -> None:
    proxies = _default_scene_proxies()
    floor_only = [{"proxy_id": "floor", "category": "floor", "geom_type": "plane", "pos": [0, 0, 0], "size": [1, 1, 0.1], "collision_enabled": True}]
    assert preview._xy_clearance([0, 0], floor_only[0]) is None
    assert preview._xy_clearance([0, 0], {"collision_enabled": True, "geom_type": "sphere", "category": "obstacle"}) is None
    assert preview._xy_clearance([0, 0], {"collision_enabled": True, "geom_type": "box", "category": "obstacle", "pos": [0], "size": [1]}) is None
    inside = preview._xy_clearance([0, 0], {"collision_enabled": True, "geom_type": "box", "category": "obstacle", "pos": [0, 0, 0], "size": [1, 1, 1]})
    outside = preview._xy_clearance([5, 0], {"collision_enabled": True, "geom_type": "box", "category": "obstacle", "pos": [0, 0, 0], "size": [1, 1, 1]})
    assert inside < 0
    assert outside > 0
    assert preview._minimum_clearance([0, 0], floor_only) == (999.0, None)
    assert preview._planner_bounds({"route_planner_bounds": {"x_min": -1, "x_max": 1, "y_min": -2, "y_max": 2}}, None) == (-1.0, 1.0, -2.0, 2.0)
    assert preview._planner_bounds({}, floor_only) == (-1.0, 1.0, -1.0, 1.0)
    assert preview._planner_bounds({}, []) == (-3.5, 3.5, -6.5, 6.5)
    assert preview._snap_to_clear_point([0, 0], proxies=[{"proxy_id": "block", "collision_enabled": True, "geom_type": "box", "category": "obstacle", "pos": [0, 0, 0], "size": [10, 10, 1]}], bounds=(-1, 1, -1, 1), min_clearance=99, grid_step=0.5, max_radius_m=0.5)
    assert preview._route_min_clearance([[0, 0, 0.8]], floor_only) == 999.0
    assert preview._interpolate_route([[1, 2, 3]], 0.5) == ([1.0, 2.0, 3.0], 0.0)
    assert preview._interpolate_route([[1, 2, 3], [1, 2, 3]], 0.5) == ([1.0, 2.0, 3.0], 0.0)
    assert preview._interpolate_route([[0, 0, 0.8], [1, 0, 0.8], [1, 1, 0.8]], 0.75)[0][:2] == [1.0, 0.5]

    preferred_task = {"task_id": "custom", "target_pose_xyz": [2, 2, 0.8], "preferred_route_waypoints": [[1, 1]]}
    spawn = {"spawn_id": "spawn", "pose_xyz_yaw": [0, 0, 0.8, 0], "valid_for_execution": False}
    assert len(preview._route_points(spawn, preferred_task)) == 3
    for task_id in [
        "navigate_chalkboard_inspect",
        "desk_object_contact_check",
        "inspect_shelf_desk_zone",
        "clear_floor_obstruction_route",
        "carry_object_to_drop_zone",
        "other",
    ]:
        route = preview._route_points(
            {"spawn_id": "normal", "pose_xyz_yaw": [0, 0, 0.8, 0]},
            {"task_id": task_id, "target_pose_xyz": [1, 1, 0.8]},
        )
        assert route[0][:2] == [0, 0]
    blocked_route = preview._route_points(
        {"spawn_id": "blocked_occluded_route_variant", "pose_xyz_yaw": [0, 0, 0.8, 0]},
        {"task_id": "navigate_chalkboard_inspect", "target_pose_xyz": [1, 1, 0.8]},
    )
    assert blocked_route[1][:2] == [1.55, -0.45]

    root = ET.fromstring("<mujoco><worldbody><body name='pelvis'><camera name='existing'/></body></worldbody></mujoco>")
    assert preview._add_camera_to_body(root, "missing", {"name": "cam", "pos": "0 0 0", "xyaxes": "1 0 0 0 1 0", "fovy": "90"}) is False
    assert preview._add_camera_to_body(root, "pelvis", {"name": "existing", "pos": "0 0 0", "xyaxes": "1 0 0 0 1 0", "fovy": "90"}) is True
    assert preview._add_camera_to_body(root, "pelvis", {"name": "new", "pos": "0 0 0", "xyaxes": "1 0 0 0 1 0", "fovy": "90"}) is True

    source_xml = tmp_path / "source-g1.xml"
    output_xml = tmp_path / "with-cameras.xml"
    source_xml.write_text("<mujoco/>", encoding="utf-8")

    def fake_absolute_meshes(_source: Path, base_xml: Path) -> None:
        base_xml.write_text(
            "<mujoco><worldbody><body name='pelvis'/><body name='right_wrist_yaw_link'/></worldbody></mujoco>",
            encoding="utf-8",
        )

    monkeypatch.setattr(preview, "_write_g1_xml_with_absolute_meshes", fake_absolute_meshes)
    camera_manifest = preview._write_g1_xml_with_eval_cameras(source_xml, output_xml)
    assert camera_manifest["camera_insertions"]["robot_pov_head"] is True
    assert output_xml.is_file()

    preview._write_generated_site_scene_xml(
        output_path=tmp_path / "scene.xml",
        g1_xml=tmp_path / "g1.xml",
        proxies=[{"proxy_id": "floor", "geom_type": "plane", "pos": [0, 0, 0], "size": [1, 1, 0.1], "rgba": [1, 1, 1, 1], "collision_enabled": True}, {"proxy_id": "box", "geom_type": "box", "pos": [0, 0, 1], "size": [1, 1, 1], "rgba": [1, 0, 0, 1], "collision_enabled": False}],
        proxy_obj=None,
    )
    assert (tmp_path / "scene.xml").is_file()

    forward_calls: list[str] = []
    data = SimpleNamespace(qpos=np.zeros(8), qvel=np.ones(8))
    preview._set_root_pose(
        model=object(),
        data=data,
        mujoco_module=SimpleNamespace(mj_forward=lambda *_args: forward_calls.append("forward")),
        base_qpos=np.zeros(8),
        root_qpos=0,
        pose=[1, 2, 3],
        yaw=0.0,
    )
    assert forward_calls == ["forward"]
    assert list(data.qpos[:3]) == [1, 2, 3]

    contact_data = SimpleNamespace(
        ncon=2,
        contact=[SimpleNamespace(geom1=1, geom2=2, dist=-0.1), SimpleNamespace(geom1=3, geom2=4, dist=0.2)],
    )
    fake_mujoco_names = SimpleNamespace(
        mjtObj=SimpleNamespace(mjOBJ_GEOM=1),
        mj_id2name=lambda _model, _obj, geom_id: {1: "teacher_desk", 2: "robot", 3: "other", 4: "robot"}.get(geom_id),
    )
    assert len(preview._contact_scene_pairs(object(), contact_data, fake_mujoco_names)) == 1

    class FakeCamera:
        def __init__(self) -> None:
            self.type = None
            self.lookat = [0, 0, 0]
            self.distance = 0
            self.azimuth = 0
            self.elevation = 0

    fake_camera_mod = SimpleNamespace(MjvCamera=FakeCamera, mjtCamera=SimpleNamespace(mjCAMERA_FREE="free"))
    assert preview._frame_camera(camera_id="third_person", task={}, pose=[1, 2, 3], yaw=0.0, mujoco_module=fake_camera_mod).distance == 3.0
    assert preview._frame_camera(camera_id="task_focus", task={"target_pose_xyz": [2, 3, 4]}, pose=[1, 2, 3], yaw=0.0, mujoco_module=fake_camera_mod).azimuth == 225.0
    assert preview._frame_camera(camera_id="other", task={}, pose=[1, 2, 3], yaw=0.0, mujoco_module=fake_camera_mod).azimuth == 135.0

    def fake_run(command, **kwargs):
        if command[0] == "ffmpeg":
            Path(command[-1]).write_bytes(b"mp4")
            return subprocess.CompletedProcess(command, 0, stderr="")
        return subprocess.CompletedProcess(command, 0, stdout=json.dumps({"streams": [{"duration": "1.5", "nb_frames": "12", "width": 640, "height": 360}]}), stderr="")

    monkeypatch.setattr(preview.subprocess, "run", fake_run)
    video = preview._write_video_from_frames(frames_dir=tmp_path, output_path=tmp_path / "out.mp4", fps=8)
    assert video["status"] == "complete"
    assert preview._ffprobe_video(tmp_path / "out.mp4")["frame_count"] == 12
    monkeypatch.setattr(preview.subprocess, "run", lambda command, **kwargs: subprocess.CompletedProcess(command, 2, stdout="", stderr="bad"))
    assert preview._ffprobe_video(tmp_path / "bad.mp4")["status"] == "blocked"

    blocked_status = preview._score_attempt(run={}, task={}, spawn_validation={"blockers": ["spawn_bad"]}, min_route_clearance=1, final_error_m=0)
    failed_status = preview._score_attempt(run={}, task={"success_thresholds": {"minimum_clearance_m": 1, "target_tolerance_m": 0.1}}, spawn_validation={}, min_route_clearance=0, final_error_m=2)
    passed_status = preview._score_attempt(run={}, task={}, spawn_validation={}, min_route_clearance=1, final_error_m=0)
    assert blocked_status[0] == "blocked"
    assert failed_status[0] == "failed"
    assert passed_status[0] == "passed"
    assert preview._task_by_id([{"task_id": "a"}])["a"]["task_id"] == "a"
    assert preview._spawn_by_id([{"spawn_id": "s"}])["s"]["spawn_id"] == "s"

    class FakeModel:
        nq = 8
        nv = 8
        nbody = 2
        ngeom = 3
        ncam = 2
        jnt_qposadr = [0]
        key_qpos = [np.zeros(8)]
        qpos0 = np.zeros(8)

    class FakeRenderer:
        def __init__(self, *_args, **_kwargs) -> None:
            self.closed = False

        def update_scene(self, _data, camera=None) -> None:
            if camera == "robot_pov_head":
                raise RuntimeError("missing camera")

        def render(self):
            return np.zeros((4, 5, 3), dtype=np.uint8)

        def close(self) -> None:
            self.closed = True

    fake_mujoco = ModuleType("mujoco")
    fake_mujoco.MjModel = SimpleNamespace(from_xml_path=lambda _path: FakeModel())
    fake_mujoco.MjData = lambda _model: SimpleNamespace(qpos=np.zeros(8), qvel=np.zeros(8), ncon=1, contact=[SimpleNamespace(geom1=1, geom2=2, dist=-0.01)])
    fake_mujoco.mjtObj = SimpleNamespace(mjOBJ_JOINT=1, mjOBJ_KEY=2, mjOBJ_GEOM=3)
    fake_mujoco.mjtCamera = SimpleNamespace(mjCAMERA_FREE="free")
    fake_mujoco.MjvCamera = FakeCamera
    fake_mujoco.mj_name2id = lambda _model, obj, name: 0 if name in {"floating_base_joint", "stand"} else -1
    fake_mujoco.mj_id2name = lambda _model, _obj, geom_id: "teacher_desk" if geom_id == 1 else "robot"
    fake_mujoco.mj_forward = lambda *_args: None
    fake_mujoco.Renderer = FakeRenderer
    monkeypatch.setitem(sys.modules, "mujoco", fake_mujoco)
    monkeypatch.setattr(preview, "_write_video_from_frames", lambda **kwargs: {"path": str(kwargs["output_path"]), "status": "complete", "size_bytes": 3})
    monkeypatch.setattr(preview, "_ffprobe_video", lambda path: {"path": str(path), "status": "complete"})
    task = {"task_id": "carry_object_to_drop_zone", "target_pose_xyz": [1, 1, 0.8], "success_thresholds": {"target_tolerance_m": 0.1, "minimum_clearance_m": 0.1}, "target_id": "drop", "object_ids": ["obj"]}
    spawn_manifest = {"spawns": [{"spawn_id": "spawn", "pose_xyz_yaw": [0, 0, 0.8, 0], "valid_for_execution": True, "blockers": []}]}
    matrix = build_scenario_eval_matrix(
        job_id="job",
        tasks=[task],
        spawns=spawn_manifest["spawns"],
        camera_ids=["pov", "overhead", "task_focus"],
        generated_at="2026-06-20T00:00:00+00:00",
    )
    render_result = preview._render_episodes(
        job_dir=tmp_path / "render",
        matrix=matrix,
        tasks=[task],
        spawn_manifest=spawn_manifest,
        proxies=proxies,
        generated_scene_xml=tmp_path / "scene.xml",
        steps=2,
        fps=8,
        camera_ids=["pov", "overhead", "task_focus"],
    )
    assert render_result["status"] == "completed"
    assert render_result["attempts"][0]["failure_label_ids"]

    clear_task = {"task_id": "clear_floor_obstruction_route", "target_pose_xyz": [1, 1, 0.8], "success_thresholds": {"target_tolerance_m": 0.1, "minimum_clearance_m": 0.1}, "target_id": "clear", "object_ids": ["obstruction"]}
    mixed_spawn_manifest = {
        "spawns": [
            {"spawn_id": "spawn", "pose_xyz_yaw": [0, 0, 0.8, 0], "valid_for_execution": True, "blockers": []},
            {"spawn_id": "invalid", "pose_xyz_yaw": [0, 0, 0.8, 0], "valid_for_execution": False, "blockers": ["bad"]},
            {"spawn_id": "blocked_occluded_route_variant", "pose_xyz_yaw": [0, 0, 0.8, 0], "valid_for_execution": True, "blockers": []},
        ]
    }
    mixed_matrix = {
        "runs": [
            "not-a-mapping",
            {"scenario_eval_run_id": "r1", "episode_id": "e1", "task_id": "carry_object_to_drop_zone", "spawn_id": "spawn", "target_pose": [1, 1, 0.8]},
            {"scenario_eval_run_id": "r2", "episode_id": "e2", "task_id": "carry_object_to_drop_zone", "spawn_id": "invalid", "route_waypoints": [[0, 0, 0.8], [1, 1, 0.8]], "target_pose": [1, 1, 0.8]},
            {"scenario_eval_run_id": "r3", "episode_id": "e3", "task_id": "clear_floor_obstruction_route", "spawn_id": "blocked_occluded_route_variant", "route_waypoints": [[0, 0, 0.8], [1, 1, 0.8]], "target_pose": [1, 1, 0.8]},
        ]
    }
    mixed_render = preview._render_episodes(
        job_dir=tmp_path / "mixed-render",
        matrix=mixed_matrix,
        tasks=[task, clear_task],
        spawn_manifest=mixed_spawn_manifest,
        proxies=proxies,
        generated_scene_xml=tmp_path / "scene.xml",
        steps=2,
        fps=8,
        camera_ids=["pov"],
    )
    assert len(mixed_render["attempts"]) == 3

    missing_joint_mujoco = ModuleType("mujoco")
    missing_joint_mujoco.MjModel = SimpleNamespace(from_xml_path=lambda _path: FakeModel())
    missing_joint_mujoco.MjData = fake_mujoco.MjData
    missing_joint_mujoco.mjtObj = fake_mujoco.mjtObj
    missing_joint_mujoco.mj_name2id = lambda *_args: -1
    missing_joint_mujoco.Renderer = FakeRenderer
    monkeypatch.setitem(sys.modules, "mujoco", missing_joint_mujoco)
    assert preview._render_episodes(
        job_dir=tmp_path / "render-blocked",
        matrix=matrix,
        tasks=[task],
        spawn_manifest=spawn_manifest,
        proxies=proxies,
        generated_scene_xml=tmp_path / "scene.xml",
        steps=2,
        fps=8,
        camera_ids=["pov"],
    )["blockers"] == ["unitree_g1_floating_base_joint_missing"]

    artifacts = preview._write_job_artifacts(
        job_dir=tmp_path / "artifacts",
        job_id="job",
        generated_at="2026-06-20T00:00:00+00:00",
        scene_asset_inspection={"assets": []},
        scene_conversion_report={"status": "completed"},
        proxies=proxies[:2],
        generated_proxy_obj={"status": "completed"},
        proxy_source_manifest={"source": "test"},
        spawn_manifest=spawn_manifest,
        matrix=matrix,
        camera_manifest={"status": "completed"},
        episode_manifest={"status": "completed"},
        render_result=render_result,
        proof_flags={"mujoco_collision_scene_source": "mjcf_proxy", "collision_dynamics_validated": False},
    )
    assert artifacts["job_run_manifest"]["status"] == "completed"
    counts = preview._counts_by_key(
        [{"task_id": "a", "status": "blocked"}, {"task_id": "a", "success": True}, {"task_id": "b", "success": False}],
        "task_id",
    )
    assert counts[0]["blocked"] == 1
    assert counts[0]["passed"] == 1

    ply = tmp_path / "input.ply"
    ply.write_text("ply\nformat ascii 1.0\nend_header\n", encoding="utf-8")
    spz = tmp_path / "input.spz"
    spz.write_bytes(b"SPZ")
    g1_root = tmp_path / "g1"
    g1_root.mkdir()
    (g1_root / "g1.xml").write_text("<mujoco/>", encoding="utf-8")
    monkeypatch.setattr(preview.platform, "system", lambda: "Linux")
    monkeypatch.setattr(preview, "_resolve_g1_model_root", lambda **_kwargs: g1_root)
    monkeypatch.setattr(preview, "_write_g1_xml_with_eval_cameras", lambda source, output: {"source_xml": str(source), "generated_eval_camera_xml": str(output)})
    monkeypatch.setattr(preview, "_asset_source_manifest", lambda root: {"source": str(root)})
    monkeypatch.setattr(preview, "_probe_mujoco_mesh_support", lambda _output_dir: {"status": "blocked"})
    monkeypatch.setattr(preview, "_render_episodes", lambda **_kwargs: render_result)
    completed = preview.run_g1_site_3dgs_mujoco_preview(
        ply_asset=ply,
        spz_asset=spz,
        job_id="job",
        job_root=tmp_path / "jobs",
        g1_model_root=g1_root,
        task_limit=1,
        spawn_limit=1,
        camera_ids=["pov"],
        generated_at="2026-06-20T00:00:00+00:00",
    )
    assert completed["status"] == "completed"
    with pytest.raises(ValueError, match="unknown camera ids"):
        preview.run_g1_site_3dgs_mujoco_preview(
            ply_asset=ply,
            spz_asset=spz,
            job_root=tmp_path / "jobs",
            g1_model_root=g1_root,
            camera_ids=["bad"],
        )
    monkeypatch.setattr(preview, "_render_episodes", lambda **_kwargs: {"status": "blocked", "blockers": ["render_failed"]})
    blocked = preview.run_g1_site_3dgs_mujoco_preview(
        ply_asset=ply,
        spz_asset=spz,
        job_id="blocked",
        job_root=tmp_path / "jobs",
        g1_model_root=g1_root,
        task_limit=1,
        spawn_limit=1,
        camera_ids=["pov"],
        generated_at="2026-06-20T00:00:00+00:00",
    )
    assert blocked["status"] == "blocked"
    assert preview._parse_camera_ids(None) is None
    assert preview._parse_camera_ids("pov,third person,,") == ["pov", "third_person"]
    monkeypatch.setattr(preview, "run_g1_site_3dgs_mujoco_preview", lambda **_kwargs: completed)
    assert preview.main(["--ply-asset", str(ply), "--spz-asset", str(spz), "--job-root", str(tmp_path / "jobs"), "--camera-ids", "pov"]) == 0
    assert json.loads(capsys.readouterr().out)["status"] == "completed"
    monkeypatch.setattr(preview, "run_g1_site_3dgs_mujoco_preview", lambda **_kwargs: {"status": "blocked", "job_dir": "x"})
    assert preview.main(["--ply-asset", str(ply), "--spz-asset", str(spz)]) == 1
