"""Start the policy server and prove its identity-bound control plane is ready.

A listening socket is not readiness.  One shipped server in this repo writes
``model_loaded_ready_to_serve`` before it calls ``serve_forever``, so a port
check would report a server that cannot yet serve.  Loading a 12.4 GB checkpoint
also takes far longer than binding a port, and an episode that starts too early
fails in a way that looks like a policy problem rather than a startup race.

Readiness here means a completed transport handshake plus exact server identity
and modality validation.  It deliberately sends no observation and requests no
action: a synthetic readiness inference would advance policy RNG/history before
the first retained episode observation.  Action shape and finite-value checks
therefore remain at the episode boundary, where the queried observation is
already sealed.

Runs under the policy venv's interpreter, never Isaac's.
"""

from __future__ import annotations

import hashlib
import json
import os
import queue
import re
import signal
import subprocess
import sys
import threading
import time
from pathlib import Path
from collections.abc import Mapping
from typing import Any

try:  # repository package
    from blueprint_pipeline.native_task_isaaclab_launch import (
        NATIVE_TASK_ARENA_DEVICE,
    )
except ModuleNotFoundError:  # flat provider-bundle layout
    # The provisioning script is generated by the repository package and
    # exports the shared launcher constant before this flat worker starts.
    # Refuse a missing binding rather than duplicate the device literal here.
    NATIVE_TASK_ARENA_DEVICE = os.environ[
        "BLUEPRINT_NATIVE_TASK_ARENA_DEVICE"
    ]

SCHEMA_VERSION = "adp009d_policy_server_worker.v2"

DEFAULT_HOST = "127.0.0.1"
DEFAULT_PORT = 8000
# Loading 12.4 GB of weights dominates this; a port appears long before.
READINESS_TIMEOUT_SECONDS = 900.0
READINESS_POLL_SECONDS = 10.0
# A readiness deadline is meaningless if one import, client constructor, ping,
# or metadata call can occupy the polling thread forever.  This bound is shorter
# than the overall model-load allowance and leaves the outer loop free to
# observe process exit and its own deadline.
# Identity/modality handshakes should be much cheaper than inference, while
# model loading can still delay the first successful metadata response. Keep a
# bounded attempt so a vendor client constructor cannot starve the outer
# readiness deadline.
HANDSHAKE_ATTEMPT_TIMEOUT_SECONDS = 120.0
SERVER_LOG_TAIL_BYTES = 32_768
FAILED_SERVER_TERMINATE_TIMEOUT_SECONDS = 10.0
READY_SERVER_TERMINATE_TIMEOUT_SECONDS = 10.0

TRANSPORT_OPENPI_WEBSOCKET = "openpi_websocket"
TRANSPORT_GROOT_ZMQ = "groot_zmq"
GROOT_DROID_EMBODIMENT_TAG = "OXE_DROID_RELATIVE_EEF_RELATIVE_JOINT"

# Read from each vendor runtime rather than assumed: openpi serves over a
# websocket on 8000 via scripts/serve_policy.py, while GR00T's client is
# gr00t.policy.server_client.PolicyClient over ZMQ, defaulting to 5555.  They
# share neither a transport nor a launch command, so a single hardcoded form
# can only ever serve one of them.
CANDIDATE_TRANSPORTS = {
    "pi05_droid": TRANSPORT_OPENPI_WEBSOCKET,
    "groot_n17_droid": TRANSPORT_GROOT_ZMQ,
    "groot_n16_droid": TRANSPORT_GROOT_ZMQ,
    "cosmos3_edge_policy_droid": TRANSPORT_OPENPI_WEBSOCKET,
}
CANDIDATE_DEFAULT_PORTS = {
    TRANSPORT_OPENPI_WEBSOCKET: 8000,
    TRANSPORT_GROOT_ZMQ: 5555,
}


class HandshakeAttemptTimeout(TimeoutError):
    """One readiness attempt starved the poll loop past its own bound."""


def transport_for(candidate_id: str) -> str:
    if candidate_id not in CANDIDATE_TRANSPORTS:
        raise RuntimeError(f"policy_server_unknown_candidate:{candidate_id}")
    return CANDIDATE_TRANSPORTS[candidate_id]


IDENTITY_BOUND_OPENPI_SERVER_MODULE = "openpi_droid_policy_runtime.py"


def build_serve_command(
    *,
    candidate_id: str,
    python: str,
    source_root: str,
    checkpoint_root: str,
    port: int,
    policy_spec_path: str | None = None,
    checkpoint_inventory_path: str | None = None,
    runtime_dir: str | Path | None = None,
    host: str = DEFAULT_HOST,
) -> list[str]:
    """The launch command for this candidate's own server.

    openpi's stock ``scripts/serve_policy.py`` publishes empty websocket
    metadata by design. The episode client is
    ``OpenPIWebsocketDroidPolicyClient``, whose ``__init__`` validates fourteen
    identity fields plus local checkpoint verification, so a stock server is
    refused *after* a full Isaac boot and scene build have been paid for. It is
    therefore not a server this lane can ever launch, and the fallback is
    removed rather than left as a trap.

    Instead we launch Blueprint's identity-bound wrapper around the same pinned
    upstream server, matching the pattern the cosmos lane already proved: a repo
    module that loads the unmodified official server class and serves it with
    verified identity metadata. Its spec comes from the same sealed execution
    spec the client validates against, so server and client cannot disagree.

    GR00T keeps its own launch: it shares neither transport nor CLI with openpi.
    """

    transport = transport_for(candidate_id)
    if transport == TRANSPORT_OPENPI_WEBSOCKET:
        missing = sorted(
            name
            for name, value in (
                ("policy_spec", policy_spec_path),
                ("checkpoint_inventory", checkpoint_inventory_path),
            )
            if not value
        )
        if missing:
            # Failing here is the point. The only other command that could be
            # produced is a stock server the episode is guaranteed to refuse.
            raise RuntimeError(
                "policy_server_identity_inputs_missing:" + ",".join(missing)
            )
        runtime = Path(runtime_dir) if runtime_dir else Path(__file__).resolve().parent
        return [
            python,
            str(runtime / IDENTITY_BOUND_OPENPI_SERVER_MODULE),
            "--policy-spec",
            str(policy_spec_path),
            "--checkpoint-dir",
            checkpoint_root,
            "--checkpoint-inventory",
            str(checkpoint_inventory_path),
            "--host",
            host,
            "--port",
            str(port),
        ]
    return [
        python,
        str(Path(source_root, "gr00t", "eval", "run_gr00t_server.py")),
        "--model-path",
        checkpoint_root,
        "--embodiment-tag",
        GROOT_DROID_EMBODIMENT_TAG,
        "--device",
        # one shared constant: this is the single place the policy server and
        # Isaac must agree about which card they co-reside on
        NATIVE_TASK_ARENA_DEVICE,
        "--host",
        DEFAULT_HOST,
        "--port",
        str(port),
    ]


def _groot_adapter_types():
    try:  # flat provider bundle
        from groot_n17_droid_policy_runtime import (
            GrootN17DroidPolicyClient,
            GrootN17DroidPolicySpec,
            validate_worker_identity_receipt,
        )
    except ModuleNotFoundError:  # repository package
        from .groot_n17_droid_policy_runtime import (
            GrootN17DroidPolicyClient,
            GrootN17DroidPolicySpec,
            validate_worker_identity_receipt,
        )
    return (
        GrootN17DroidPolicyClient,
        GrootN17DroidPolicySpec,
        validate_worker_identity_receipt,
    )


def _openpi_adapter_types():
    try:  # flat provider bundle
        from openpi_droid_policy_runtime import (
            OpenPIDroidPolicySpec,
            OpenPIWebsocketDroidPolicyClient,
            validate_arena_candidate_policy_binding,
        )
    except ModuleNotFoundError:  # repository package
        from .openpi_droid_policy_runtime import (
            OpenPIDroidPolicySpec,
            OpenPIWebsocketDroidPolicyClient,
            validate_arena_candidate_policy_binding,
        )
    return (
        OpenPIWebsocketDroidPolicyClient,
        OpenPIDroidPolicySpec,
        validate_arena_candidate_policy_binding,
    )


def attempt_handshake(
    host: str,
    port: int,
    transport: str = TRANSPORT_OPENPI_WEBSOCKET,
    worker_identity_receipt: Mapping[str, Any] | None = None,
    policy_spec: Mapping[str, Any] | None = None,
    candidate_id: str | None = None,
) -> dict:
    """Validate the candidate's control plane without querying the policy."""

    client = None
    try:
        if transport == TRANSPORT_GROOT_ZMQ:
            if worker_identity_receipt is None:
                raise RuntimeError("groot_worker_identity_receipt_missing")
            client_type, spec_type, _ = _groot_adapter_types()
            client = client_type(
                spec=spec_type(),
                worker_identity_receipt=worker_identity_receipt,
                host=host,
                port=int(port),
            )
            adapter_evidence = client.evidence_summary()
        else:
            if policy_spec is None:
                raise RuntimeError("openpi_policy_spec_missing_for_handshake")
            if candidate_id is None:
                raise RuntimeError("openpi_candidate_id_missing_for_handshake")
            client_type, spec_type, validate_binding = _openpi_adapter_types()
            spec = spec_type(**dict(policy_spec))
            validate_binding(candidate_id=candidate_id, spec=spec)
            client = client_type(
                spec=spec,
                host=host,
                port=int(port),
            )
            adapter_evidence = client.evidence_summary()
        if adapter_evidence.get("identity_verified") is not True:
            raise RuntimeError("policy_server_identity_not_verified")
        if adapter_evidence.get("last_inference_evidence") is not None:
            raise RuntimeError("policy_server_handshake_advanced_policy_state")
        if getattr(client, "candidate_policy_queried", False) is not False:
            raise RuntimeError("policy_server_handshake_queried_candidate")
        result = {
            "handshake_completed": True,
            "readiness_method": "identity_bound_transport_handshake_without_inference",
            "candidate_policy_queried": False,
            "candidate_inference_performed": False,
            "policy_state_advanced": False,
            "server_metadata": adapter_evidence.get("server_metadata"),
            "policy_adapter_evidence": adapter_evidence,
        }
        return result
    finally:
        if client is not None:
            close = getattr(client, "close", None)
            if callable(close):
                close()


def _attempt_handshake_with_timeout(
    *,
    host: str,
    port: int,
    transport: str,
    timeout_seconds: float,
    worker_identity_receipt: Mapping[str, Any] | None = None,
    policy_spec: Mapping[str, Any] | None = None,
    candidate_id: str | None = None,
) -> dict:
    """Run one vendor attempt in a daemon thread with a real wall deadline.

    Python cannot safely kill a blocked import or third-party constructor.  A
    daemon thread lets the worker emit its failure receipt and exit instead of
    joining the stuck call during interpreter shutdown.  After a timeout the
    caller fails immediately; it never accumulates more abandoned attempts.
    """

    timeout = float(timeout_seconds)
    if timeout <= 0:
        raise HandshakeAttemptTimeout("policy_server_handshake_attempt_timeout_invalid")

    result_queue: queue.Queue[tuple[bool, Any]] = queue.Queue(maxsize=1)

    def _run() -> None:
        try:
            payload = attempt_handshake(
                host,
                port,
                transport,
                worker_identity_receipt,
                policy_spec,
                candidate_id,
            )
            result_queue.put((True, payload))
        except BaseException as exc:  # noqa: BLE001 - re-raised on the polling thread
            result_queue.put((False, exc))

    thread = threading.Thread(
        target=_run,
        name=f"policy-handshake-{transport}",
        daemon=True,
    )
    thread.start()
    thread.join(timeout)
    if thread.is_alive():
        raise HandshakeAttemptTimeout(
            f"policy_server_handshake_attempt_timed_out:{timeout:.3f}s"
        )

    succeeded, payload = result_queue.get_nowait()
    if succeeded:
        return dict(payload)
    if isinstance(payload, BaseException):
        raise payload
    raise RuntimeError("policy_server_handshake_attempt_returned_invalid_result")


def _server_log_summary(path: Path) -> dict[str, Any]:
    """Retain bounded diagnostics in the receipt as well as the output file."""

    if not path.is_file():
        return {
            "path": str(path),
            "present": False,
            "size_bytes": 0,
            "sha256": None,
            "tail": None,
        }
    data = path.read_bytes()
    return {
        "path": str(path),
        "present": True,
        "size_bytes": len(data),
        "sha256": "sha256:" + hashlib.sha256(data).hexdigest(),
        "tail": data[-SERVER_LOG_TAIL_BYTES:].decode("utf-8", errors="replace"),
        "tail_bytes_limit": SERVER_LOG_TAIL_BYTES,
    }


def _stop_failed_server(process: subprocess.Popen | None) -> dict[str, Any]:
    """Ensure a server that failed readiness cannot contend with Isaac.

    A readiness timeout used to return ``rc=1`` while leaving the JAX child
    alive.  The provider runner then started Isaac beside a model process that
    still owned the GPU, turning a useful bounded failure into another opaque
    and billable stall.
    """

    if process is None:
        return {"status": "not_started", "exit_code": None}
    exit_code = process.poll()
    if exit_code is not None:
        return {"status": "already_exited", "exit_code": int(exit_code)}
    process.terminate()
    try:
        exit_code = process.wait(timeout=FAILED_SERVER_TERMINATE_TIMEOUT_SECONDS)
        return {"status": "terminated", "exit_code": int(exit_code)}
    except subprocess.TimeoutExpired:
        process.kill()
        exit_code = process.wait(timeout=FAILED_SERVER_TERMINATE_TIMEOUT_SECONDS)
        return {"status": "killed", "exit_code": int(exit_code)}


def _canonical_digest(value: Mapping[str, Any], *, digest_field: str) -> str:
    normalized = dict(value)
    normalized.pop(digest_field, None)
    payload = json.dumps(
        normalized, sort_keys=True, separators=(",", ":"), ensure_ascii=False
    )
    return "sha256:" + hashlib.sha256(payload.encode("utf-8")).hexdigest()


def _linux_process_command(pid: int) -> list[str] | None:
    """Read one live Linux process identity, or report that the PID is absent."""

    try:
        payload = Path(f"/proc/{pid}/cmdline").read_bytes()
    except FileNotFoundError:
        return None
    if not payload:
        # A zombie has exited and can no longer serve even if PID 1 has not yet
        # reaped its process-table entry.
        return None
    return [
        part.decode("utf-8", errors="surrogateescape")
        for part in payload.split(b"\0")
        if part
    ]


def terminate_ready_server_from_receipt(
    receipt_path: str | Path,
    *,
    command_reader: Any = _linux_process_command,
    signal_process: Any = os.kill,
    monotonic: Any = time.monotonic,
    sleep: Any = time.sleep,
    terminate_timeout_seconds: float = READY_SERVER_TERMINATE_TIMEOUT_SECONDS,
) -> dict[str, Any]:
    """Terminate only the exact ready server named by its retained receipt.

    The launcher that owns ``Popen`` has already exited after readiness, so the
    bundle supervisor cannot call ``Popen.wait``. It instead verifies the
    receipt command against ``/proc/<pid>/cmdline`` before signalling and polls
    that same identity until it is observably gone. A reused or mismatched PID
    is never signalled.
    """

    path = Path(receipt_path)
    result: dict[str, Any] = {
        "schema_version": "adp009d_policy_server_teardown.v1",
        "status": "blocked",
        "policy_server_process_terminated": False,
        "server_receipt_path": str(path),
        "server_pid": None,
        "exact_process_identity_verified": False,
        "termination_method": None,
        "blockers": [],
    }
    try:
        receipt_bytes = path.read_bytes()
        receipt = json.loads(receipt_bytes)
    except (OSError, json.JSONDecodeError):
        result["blockers"].append(
            "policy_server_teardown_receipt_missing_or_invalid"
        )
        return result
    result["server_receipt_sha256"] = "sha256:" + hashlib.sha256(
        receipt_bytes
    ).hexdigest()

    pid = receipt.get("server_pid")
    command = receipt.get("command")
    result["candidate_id"] = receipt.get("candidate_id")
    result["server_pid"] = pid
    if receipt.get("status") != "ready":
        result["blockers"].append("policy_server_teardown_server_was_not_ready")
        return result
    if not isinstance(pid, int) or isinstance(pid, bool) or pid <= 0:
        result["blockers"].append("policy_server_teardown_pid_invalid")
        return result
    if (
        not isinstance(command, list)
        or not command
        or not all(isinstance(part, str) and part for part in command)
    ):
        result["blockers"].append("policy_server_teardown_command_invalid")
        return result

    try:
        observed_command = command_reader(pid)
    except OSError as exc:
        result["blockers"].append(
            f"policy_server_teardown_identity_unreadable:{type(exc).__name__}"
        )
        return result
    if observed_command is None:
        result.update(
            {
                "status": "completed",
                "policy_server_process_terminated": True,
                "termination_method": "already_exited",
            }
        )
        return result
    if observed_command != command:
        result["blockers"].append("policy_server_teardown_pid_identity_mismatch")
        return result
    result["exact_process_identity_verified"] = True

    def wait_until_exact_process_exits(timeout_seconds: float) -> bool:
        deadline = monotonic() + timeout_seconds
        while True:
            current = command_reader(pid)
            if current is None or current != command:
                return True
            if monotonic() >= deadline:
                return False
            sleep(min(0.1, max(0.0, deadline - monotonic())))

    try:
        signal_process(pid, signal.SIGTERM)
    except ProcessLookupError:
        result.update(
            {
                "status": "completed",
                "policy_server_process_terminated": True,
                "termination_method": "exited_before_sigterm",
            }
        )
        return result
    if wait_until_exact_process_exits(terminate_timeout_seconds):
        result.update(
            {
                "status": "completed",
                "policy_server_process_terminated": True,
                "termination_method": "sigterm",
            }
        )
        return result

    try:
        signal_process(pid, signal.SIGKILL)
    except ProcessLookupError:
        pass
    if wait_until_exact_process_exits(terminate_timeout_seconds):
        result.update(
            {
                "status": "completed",
                "policy_server_process_terminated": True,
                "termination_method": "sigkill",
            }
        )
        return result
    result["blockers"].append("policy_server_teardown_process_survived_sigkill")
    return result


def _seal_ready_server_teardown(
    *, receipt_path: str | Path, result_path: str | Path, result_schema: str
) -> int:
    """Retain teardown evidence and bind it into the terminal episode result."""

    try:
        teardown = terminate_ready_server_from_receipt(receipt_path)
    except BaseException as exc:  # noqa: BLE001 - trap must retain fail-closed proof
        teardown = {
            "schema_version": "adp009d_policy_server_teardown.v1",
            "status": "blocked",
            "policy_server_process_terminated": False,
            "server_pid": None,
            "exact_process_identity_verified": False,
            "termination_method": None,
            "blockers": [
                f"policy_server_teardown_internal_error:{type(exc).__name__}"
            ],
        }
    destination = Path(result_path)
    candidate_id = str(teardown.get("candidate_id") or "unknown")
    safe_candidate_id = (
        candidate_id
        if re.fullmatch(r"[A-Za-z0-9][A-Za-z0-9._-]{0,127}", candidate_id)
        else "unknown"
    )
    teardown_path = (
        destination.parent
        / f"adp009d_policy_server_teardown.{safe_candidate_id}.v1.json"
    )
    teardown["completed_at_unix_ns"] = time.time_ns()
    teardown["teardown_digest"] = _canonical_digest(
        teardown, digest_field="teardown_digest"
    )
    teardown_path.parent.mkdir(parents=True, exist_ok=True)
    teardown_path.write_text(
        json.dumps(teardown, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )

    try:
        episode_result = json.loads(destination.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        episode_result = {
            "schema_version": result_schema,
            "status": "blocked",
            "blockers": ["native_task_arena_process_exited_without_result"],
            "candidate_policy_queried": False,
            "candidate_outcomes_accessed": False,
            "provider_zero_required_after_return": True,
        }
    bound_teardown = {
        "policy_server_process_terminated": teardown[
            "policy_server_process_terminated"
        ],
        "server_pid": teardown.get("server_pid"),
        "exact_process_identity_verified": teardown[
            "exact_process_identity_verified"
        ],
        "termination_method": teardown.get("termination_method"),
        "teardown_receipt": teardown_path.name,
        "teardown_receipt_sha256": "sha256:"
        + hashlib.sha256(teardown_path.read_bytes()).hexdigest(),
    }
    teardowns = episode_result.get("policy_server_teardowns")
    if not isinstance(teardowns, dict):
        teardowns = {}
    teardowns[safe_candidate_id] = bound_teardown
    episode_result["policy_server_teardowns"] = teardowns
    episode_result["teardown"] = bound_teardown
    if teardown["policy_server_process_terminated"] is not True:
        episode_result["status"] = "blocked"
        episode_result["scientific_outcome_admitted"] = False
        episode_result["ranking_eligible"] = False
        blockers = list(episode_result.get("blockers") or [])
        blockers.extend(teardown["blockers"])
        blockers.append("native_task_policy_server_teardown_unproven")
        episode_result["blockers"] = sorted(set(blockers))
    episode_result["result_digest"] = _canonical_digest(
        episode_result, digest_field="result_digest"
    )
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(
        json.dumps(episode_result, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    return 0 if teardown["policy_server_process_terminated"] is True else 1


def wait_for_handshake(
    *,
    host: str,
    port: int,
    timeout_seconds: float,
    process: subprocess.Popen | None,
    transport: str = TRANSPORT_OPENPI_WEBSOCKET,
    worker_identity_receipt: Mapping[str, Any] | None = None,
    policy_spec: Mapping[str, Any] | None = None,
    candidate_id: str | None = None,
) -> dict:
    """Poll until the identity-bound handshake succeeds or the server fails."""

    started = time.monotonic()
    attempts = 0
    last_error: str | None = None
    while time.monotonic() - started < timeout_seconds:
        if process is not None and process.poll() is not None:
            raise RuntimeError(
                f"policy_server_exited_before_ready:{process.returncode}"
            )
        attempts += 1
        remaining = float(timeout_seconds) - (time.monotonic() - started)
        attempt_timeout = min(HANDSHAKE_ATTEMPT_TIMEOUT_SECONDS, remaining)
        try:
            result = _attempt_handshake_with_timeout(
                host=host,
                port=port,
                transport=transport,
                timeout_seconds=attempt_timeout,
                worker_identity_receipt=worker_identity_receipt,
                policy_spec=policy_spec,
                candidate_id=candidate_id,
            )
            result["readiness_attempts"] = attempts
            result["readiness_seconds"] = round(time.monotonic() - started, 3)
            return result
        except HandshakeAttemptTimeout as exc:
            # Do not start another vendor call while the timed-out daemon may
            # still be blocked.  Preserve this exact diagnosis immediately.
            raise RuntimeError(str(exc)) from exc
        except Exception as exc:  # noqa: BLE001 - not-yet-ready is the normal case
            last_error = f"{type(exc).__name__}: {exc}"
            remaining = float(timeout_seconds) - (time.monotonic() - started)
            if remaining > 0:
                time.sleep(min(READINESS_POLL_SECONDS, remaining))
    raise RuntimeError(f"policy_server_handshake_never_completed:{last_error}")


def main(argv: list[str] | None = None) -> int:
    import argparse

    raw_argv = list(sys.argv[1:] if argv is None else argv)
    if raw_argv and raw_argv[0] == "--terminate-ready-server":
        teardown_parser = argparse.ArgumentParser(description=__doc__)
        teardown_parser.add_argument("--terminate-ready-server", action="store_true")
        teardown_parser.add_argument("--receipt", required=True)
        teardown_parser.add_argument("--result", required=True)
        teardown_parser.add_argument("--result-schema", required=True)
        teardown_args = teardown_parser.parse_args(raw_argv)
        return _seal_ready_server_teardown(
            receipt_path=teardown_args.receipt,
            result_path=teardown_args.result,
            result_schema=teardown_args.result_schema,
        )

    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--candidate-id", required=True)
    parser.add_argument("--source-root", required=True)
    parser.add_argument("--checkpoint-root", required=True)
    parser.add_argument("--python", required=True)
    parser.add_argument("--host", default=DEFAULT_HOST)
    parser.add_argument("--port", type=int, default=0)
    parser.add_argument("--log", required=True)
    parser.add_argument("--receipt", required=True)
    parser.add_argument("--worker-identity-receipt")
    parser.add_argument("--policy-spec")
    parser.add_argument("--checkpoint-inventory")
    parser.add_argument(
        "--stop-after-handshake",
        action="store_true",
        help=(
            "Stop the policy server immediately after the readiness handshake. "
            "Used by outcome-blind runtime smokes; episode serving leaves it running."
        ),
    )
    parser.add_argument(
        "--timeout-seconds", type=float, default=READINESS_TIMEOUT_SECONDS
    )
    args = parser.parse_args(raw_argv)

    if args.host not in {"127.0.0.1", "localhost", "::1"}:
        raise SystemExit("policy_server_must_be_loopback_only")

    log_path = Path(args.log)
    log_path.parent.mkdir(parents=True, exist_ok=True)

    transport = transport_for(args.candidate_id)
    port = int(args.port or CANDIDATE_DEFAULT_PORTS[transport])
    command = build_serve_command(
        candidate_id=args.candidate_id,
        python=args.python,
        source_root=args.source_root,
        checkpoint_root=args.checkpoint_root,
        port=port,
        policy_spec_path=args.policy_spec,
        checkpoint_inventory_path=args.checkpoint_inventory,
        host=args.host,
    )

    receipt: dict = {
        "schema_version": SCHEMA_VERSION,
        "candidate_id": args.candidate_id,
        "host": args.host,
        "port": port,
        "transport": transport,
        "command": command,
        "policy_interpreter": args.python,
    }

    process: subprocess.Popen | None = None
    try:
        worker_identity_receipt = None
        policy_spec = None
        if transport == TRANSPORT_GROOT_ZMQ:
            if not args.worker_identity_receipt:
                raise RuntimeError("groot_worker_identity_receipt_missing")
            identity_path = Path(args.worker_identity_receipt)
            if not identity_path.is_file():
                raise RuntimeError("groot_worker_identity_receipt_file_missing")
            worker_identity_receipt = json.loads(
                identity_path.read_text(encoding="utf-8")
            )
            _, spec_type, validate_identity = _groot_adapter_types()
            worker_identity_receipt = validate_identity(
                worker_identity_receipt, expected=spec_type()
            )
            receipt["worker_identity_receipt"] = worker_identity_receipt
        else:
            if not args.policy_spec:
                raise RuntimeError("openpi_policy_spec_file_missing")
            execution_spec = json.loads(
                Path(args.policy_spec).read_text(encoding="utf-8")
            )
            policy_spec = execution_spec.get("policy_spec")
            if not isinstance(policy_spec, Mapping):
                raise RuntimeError("openpi_policy_spec_invalid")
        with log_path.open("wb") as log_handle:
            process = subprocess.Popen(  # noqa: S603
                command, stdout=log_handle, stderr=subprocess.STDOUT
            )
            handshake = wait_for_handshake(
                host=args.host,
                port=port,
                timeout_seconds=float(args.timeout_seconds),
                process=process,
                transport=transport,
                worker_identity_receipt=worker_identity_receipt,
                policy_spec=policy_spec,
                candidate_id=args.candidate_id,
            )
        receipt.update(
            {
                "status": "ready",
                "server_pid": process.pid,
                **handshake,
            }
        )
        if args.stop_after_handshake:
            server_cleanup = _stop_failed_server(process)
            receipt["server_stopped_after_handshake"] = server_cleanup.get(
                "status"
            ) in {"already_exited", "terminated", "killed"}
            receipt["server_cleanup"] = server_cleanup
            if receipt["server_stopped_after_handshake"] is not True:
                raise RuntimeError("policy_server_smoke_cleanup_failed")
        exit_code = 0
    except Exception as exc:  # noqa: BLE001 - the failure is the evidence
        failed_server_cleanup = _stop_failed_server(process)
        receipt.update(
            {
                "status": "blocked",
                "handshake_completed": False,
                "candidate_policy_queried": False,
                "candidate_inference_performed": False,
                "policy_state_advanced": False,
                "error": f"{type(exc).__name__}: {exc}",
                "server_pid": process.pid if process else None,
                "server_exit_code": failed_server_cleanup["exit_code"],
                "failed_server_cleanup": failed_server_cleanup,
            }
        )
        exit_code = 1

    # The provider output zipper retains every bounded file in OUT_DIR, so the
    # log itself survives.  Embed its digest and tail in the receipt too: even
    # a future packaging regression cannot erase the diagnosis silently.
    receipt["server_log"] = _server_log_summary(log_path)

    Path(args.receipt).parent.mkdir(parents=True, exist_ok=True)
    Path(args.receipt).write_text(
        json.dumps(receipt, indent=2, sort_keys=True, default=str) + "\n",
        encoding="utf-8",
    )
    print(f"BLUEPRINT_ADP009D_POLICY_SERVER:{receipt['status']}")
    return exit_code


if __name__ == "__main__":
    raise SystemExit(main())
