"""Fail-closed model-parameter compatibility for released Content Agents.

The NVIDIA Content Agents release owns its task prompts and per-step sampling
defaults.  Hosted model APIs own which generation parameters are accepted.
This module joins those two contracts without changing either claim boundary:
the exact released source archive is retained, then a small digest-bound
compatibility overlay is applied to the extracted provider copy.
"""

from __future__ import annotations

import argparse
import datetime as dt
import hashlib
import json
from pathlib import Path
from typing import Any, Iterable

SCHEMA_VERSION = "content_agents_model_compatibility.v1"
OVERLAY_VERSION = "openai_default_sampling_parameters.v1"
_DEFAULT_ONLY_TEMPERATURE_MODEL_PREFIXES = ("gpt-5.6-luna",)
_VISION_RELATIVE_PATH = Path(
    "world_understanding/functions/models/vision_language_models.py"
)
_BACKEND_RELATIVE_PATH = Path(
    "world_understanding/functions/models/backends/public/openai.py"
)
_HELPER_RELATIVE_PATH = Path(
    "world_understanding/functions/models/openai_parameter_compatibility.py"
)
_HELPER_SOURCE = '''# Generated by Blueprint's digest-bound provider compatibility overlay.
"""OpenAI generation-parameter capability rules for this provider bundle."""

from __future__ import annotations


_DEFAULT_ONLY_TEMPERATURE_MODEL_PREFIXES = ("gpt-5.6-luna",)


def openai_custom_temperature_supported(model_id: str | None) -> bool:
    normalized = str(model_id or "").strip().lower()
    return not any(
        normalized == prefix or normalized.startswith(prefix + "-")
        for prefix in _DEFAULT_ONLY_TEMPERATURE_MODEL_PREFIXES
    )
'''


def _sha256(path: Path) -> str:
    return "sha256:" + hashlib.sha256(path.read_bytes()).hexdigest()


def _utc_now_iso() -> str:
    return dt.datetime.now(dt.timezone.utc).isoformat()


def _write_json(path: Path, value: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(
        json.dumps(value, indent=2, sort_keys=True) + "\n", encoding="utf-8"
    )


def openai_custom_temperature_supported(model_id: str | None) -> bool:
    """Return whether ``temperature`` may be sent for an OpenAI model.

    Snapshot suffixes inherit the base model capability.  Unknown models are
    left unchanged; their admission preflight remains responsible for proving
    their exact request profile.
    """

    normalized = str(model_id or "").strip().lower()
    return not any(
        normalized == prefix or normalized.startswith(prefix + "-")
        for prefix in _DEFAULT_ONLY_TEMPERATURE_MODEL_PREFIXES
    )


def materialize_content_agents_model_compatibility_plan(
    *, model_ids: Iterable[str], destination: str | Path
) -> dict[str, Any]:
    """Freeze the parameter policy before a provider bundle is executed."""

    normalized = sorted({str(model).strip() for model in model_ids if str(model).strip()})
    rows = [
        {
            "model_id": model,
            "omit_generation_parameters": (
                [] if openai_custom_temperature_supported(model) else ["temperature"]
            ),
        }
        for model in normalized
    ]
    plan = {
        "schema_version": SCHEMA_VERSION,
        "overlay_version": OVERLAY_VERSION,
        "models": rows,
        "overlay_required": any(row["omit_generation_parameters"] for row in rows),
        "unknown_models_preserve_released_parameters": True,
    }
    _write_json(Path(destination), plan)
    return plan


def _load_plan(path: Path) -> dict[str, Any]:
    try:
        value = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise ValueError("content_agents_model_compatibility_plan_invalid") from exc
    if (
        not isinstance(value, dict)
        or value.get("schema_version") != SCHEMA_VERSION
        or value.get("overlay_version") != OVERLAY_VERSION
        or not isinstance(value.get("models"), list)
    ):
        raise ValueError("content_agents_model_compatibility_plan_invalid")
    expected = any(
        isinstance(row, dict) and bool(row.get("omit_generation_parameters"))
        for row in value["models"]
    )
    if value.get("overlay_required") is not expected:
        raise ValueError("content_agents_model_compatibility_plan_invalid")
    return value


def _patch_openai_vlm(path: Path) -> dict[str, Any]:
    source = path.read_text(encoding="utf-8")
    before = _sha256(path)
    import_line = (
        "from world_understanding.functions.models.openai_parameter_compatibility "
        "import openai_custom_temperature_supported\n"
    )
    source_lines = source.splitlines(keepends=True)
    telemetry_imports = [
        index
        for index, line in enumerate(source_lines)
        if line.startswith("from world_understanding.telemetry import ")
    ]
    if len(telemetry_imports) != 1 or import_line in source:
        raise ValueError("content_agents_openai_vlm_overlay_anchor_invalid")
    start = source.find("class OpenAIVLM(")
    end = source.find("\nclass AnthropicVLM(", start)
    if start < 0 or end < 0:
        raise ValueError("content_agents_openai_vlm_overlay_anchor_invalid")
    block = source[start:end]
    old = "        if temperature is not None:\n"
    new = (
        "        if (\n"
        "            temperature is not None\n"
        "            and openai_custom_temperature_supported(self._model_name)\n"
        "        ):\n"
    )
    if block.count(old) != 3:
        raise ValueError("content_agents_openai_vlm_temperature_seam_changed")
    block = block.replace(old, new)
    source = source[:start] + block + source[end:]
    source_lines = source.splitlines(keepends=True)
    source_lines.insert(telemetry_imports[0] + 1, import_line)
    source = "".join(source_lines)
    compile(source, str(path), "exec")
    path.write_text(source, encoding="utf-8")
    return {
        "relative_path": _VISION_RELATIVE_PATH.as_posix(),
        "before_sha256": before,
        "after_sha256": _sha256(path),
        "temperature_call_sites_normalized": 3,
    }


def _patch_openai_chat_backend(path: Path) -> dict[str, Any]:
    source = path.read_text(encoding="utf-8")
    before = _sha256(path)
    import_anchor = "from world_understanding.functions.models.backends.registry import (\n"
    import_line = (
        "from world_understanding.functions.models.openai_parameter_compatibility "
        "import openai_custom_temperature_supported\n"
    )
    old = "    if temperature is not None:\n        chat_kwargs[\"temperature\"] = temperature\n"
    new = (
        "    if (\n"
        "        temperature is not None\n"
        "        and openai_custom_temperature_supported(model or _DEFAULT_OPENAI_MODEL)\n"
        "    ):\n"
        "        chat_kwargs[\"temperature\"] = temperature\n"
    )
    if import_anchor not in source or import_line in source or source.count(old) != 1:
        raise ValueError("content_agents_openai_chat_overlay_anchor_invalid")
    source = source.replace(import_anchor, import_line + import_anchor, 1)
    source = source.replace(old, new, 1)
    compile(source, str(path), "exec")
    path.write_text(source, encoding="utf-8")
    return {
        "relative_path": _BACKEND_RELATIVE_PATH.as_posix(),
        "before_sha256": before,
        "after_sha256": _sha256(path),
        "temperature_call_sites_normalized": 1,
    }


def apply_content_agents_model_compatibility(
    *, source_root: str | Path, plan_path: str | Path, receipt_path: str | Path
) -> dict[str, Any]:
    """Apply the frozen overlay to an extracted released-code provider copy."""

    source = Path(source_root).resolve()
    plan_file = Path(plan_path).resolve()
    receipt_file = Path(receipt_path).resolve()
    plan = _load_plan(plan_file)
    rows: list[dict[str, Any]] = []
    helper: dict[str, Any] | None = None
    status = "not_required"
    if plan["overlay_required"]:
        vision = source / _VISION_RELATIVE_PATH
        backend = source / _BACKEND_RELATIVE_PATH
        if not vision.is_file() or not backend.is_file():
            raise ValueError("content_agents_openai_compatibility_source_missing")
        helper_path = source / _HELPER_RELATIVE_PATH
        if helper_path.exists():
            raise ValueError("content_agents_openai_compatibility_helper_already_exists")
        helper_path.write_text(_HELPER_SOURCE, encoding="utf-8")
        compile(_HELPER_SOURCE, str(helper_path), "exec")
        helper = {
            "relative_path": _HELPER_RELATIVE_PATH.as_posix(),
            "sha256": _sha256(helper_path),
        }
        rows = [_patch_openai_vlm(vision), _patch_openai_chat_backend(backend)]
        status = "applied"
    receipt = {
        "schema_version": SCHEMA_VERSION,
        "generated_at": _utc_now_iso(),
        "status": status,
        "overlay_version": OVERLAY_VERSION,
        "plan_path": str(plan_file),
        "plan_sha256": _sha256(plan_file),
        "source_root": str(source),
        "models": plan["models"],
        "modified_files": rows,
        "added_helper": helper,
        "released_source_archive_remains_unmodified": True,
        "overlay_applied_only_to_extracted_provider_copy": True,
        "blockers": [],
    }
    _write_json(receipt_file, receipt)
    return receipt


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source-root", required=True)
    parser.add_argument("--plan", required=True)
    parser.add_argument("--receipt", required=True)
    args = parser.parse_args(argv)
    try:
        apply_content_agents_model_compatibility(
            source_root=args.source_root,
            plan_path=args.plan,
            receipt_path=args.receipt,
        )
    except (OSError, ValueError) as exc:
        _write_json(
            Path(args.receipt),
            {
                "schema_version": SCHEMA_VERSION,
                "generated_at": _utc_now_iso(),
                "status": "blocked",
                "blockers": [str(exc)],
            },
        )
        return 2
    return 0


if __name__ == "__main__":
    raise SystemExit(main())


__all__ = [
    "apply_content_agents_model_compatibility",
    "materialize_content_agents_model_compatibility_plan",
    "openai_custom_temperature_supported",
]
