"""Static site-evidence mappings for task/site measurement routing."""

CAPABILITY_SITE_EVIDENCE: dict[str, tuple[str, ...]] = {
    "metric_scale_supported": ("metric_scale", "robot_site_registration"),
    "mesh_supported": ("validated_mesh",),
    "convex_collider_supported": ("validated_collider",),
    "triangle_mesh_collider_supported": ("validated_collider",),
    "sdf_collider_supported": ("validated_collider",),
    "continuous_collision_supported": ("validated_collider", "robot_site_registration"),
    "thin_shell_collision_supported": ("validated_collider",),
    "two_sided_collision_supported": ("validated_collider",),
    "uncertainty_map_supported": ("coverage_uncertainty",),
    "dynamic_collision_supported": ("validated_collider", "mass_inertia"),
    "static_friction_supported": ("friction_contact",),
    "dynamic_friction_supported": ("friction_contact",),
    "anisotropic_friction_supported": ("friction_contact",),
    "rolling_friction_supported": ("friction_contact",),
    "torsional_friction_supported": ("friction_contact",),
    "contact_compliance_supported": ("material_parameters",),
    "hydroelastic_contact_supported": ("material_parameters",),
    "adhesion_supported": ("material_parameters",),
    "contact_force_output_supported": ("force_tactile",),
    "impulse_output_supported": ("force_tactile",),
    "revolute_joint_supported": ("articulation_model",),
    "prismatic_joint_supported": ("articulation_model",),
    "closed_chain_supported": ("articulation_model",),
    "mimic_joint_supported": ("articulation_model",),
    "joint_limits_supported": ("articulation_model",),
    "joint_friction_supported": ("articulation_actuation",),
    "joint_damping_supported": ("articulation_actuation",),
    "backlash_supported": ("articulation_actuation",),
    "detent_supported": ("articulation_actuation",),
    "joint_compliance_supported": ("articulation_actuation",),
    "cloth_shell_supported": ("material_parameters", "initial_material_state"),
    "anisotropic_cloth_supported": ("material_parameters",),
    "seams_supported": ("material_parameters",),
    "tearing_supported": ("material_parameters",),
    "rod_cable_supported": ("material_parameters", "initial_material_state"),
    "torsional_rod_supported": ("material_parameters",),
    "plastic_bending_supported": ("material_parameters",),
    "hyperelastic_fem_supported": ("material_parameters",),
    "nearly_incompressible_supported": ("material_parameters",),
    "viscoelastic_supported": ("material_parameters",),
    "foam_compression_supported": ("material_parameters",),
    "mpm_supported": ("material_parameters",),
    "dem_supported": ("material_parameters",),
    "granular_cohesion_supported": ("material_parameters",),
    "particle_breakage_supported": ("material_parameters",),
    "sph_supported": ("material_parameters",),
    "cfd_supported": ("material_parameters",),
    "fluid_surface_tension_supported": ("material_parameters",),
    "fluid_wetting_supported": ("material_parameters",),
    "fracture_supported": ("material_parameters",),
    "cutting_supported": ("material_parameters", "physical_specimens"),
    "tissue_model_supported": ("material_parameters", "physical_specimens"),
    "food_specific_model_supported": ("material_parameters", "physical_specimens"),
    "rgb_supported": ("calibrated_rgb",),
    "depth_supported": ("calibrated_depth",),
    "structured_light_supported": ("sensor_calibration",),
    "lidar_supported": ("calibrated_lidar",),
    "radar_supported": ("sensor_calibration",),
    "event_camera_supported": ("sensor_calibration",),
    "imu_supported": ("calibrated_imu",),
    "intrinsics_import_supported": ("sensor_calibration",),
    "extrinsics_import_supported": ("sensor_calibration",),
    "distortion_model_supported": ("sensor_calibration",),
    "rolling_shutter_supported": ("sensor_calibration",),
    "motion_blur_supported": ("sensor_calibration",),
    "isp_model_supported": ("sensor_calibration",),
    "temporal_noise_supported": ("sensor_timing",),
    "material_brdf_supported": ("lighting_coverage",),
    "transmission_refraction_supported": ("sensor_calibration",),
    "spectral_model_supported": ("sensor_calibration",),
    "sensor_timing_supported": ("sensor_timing",),
    "force_torque_supported": ("force_tactile",),
    "contact_sensor_supported": ("force_tactile",),
    "optical_tactile_supported": ("force_tactile",),
    "taxel_tactile_supported": ("force_tactile",),
    "actuator_dynamics_supported": ("robot_controller_calibration",),
    "whole_body_control_supported": ("robot_controller_calibration",),
    "impedance_control_supported": ("robot_controller_calibration",),
    "controller_latency_model_supported": ("robot_controller_calibration",),
}

EVIDENCE_SMALLEST_ACTION: dict[str, str] = {
    "metric_scale": "metric_scale_check",
    "robot_site_registration": "robot_site_registration",
    "validated_mesh": "collider_validation",
    "validated_collider": "collider_validation",
    "coverage_uncertainty": "targeted_recapture",
    "multiview_coverage": "targeted_recapture",
    "camera_poses": "targeted_recapture",
    "lighting_coverage": "targeted_recapture",
    "object_segmentation": "targeted_recapture",
    "semantic_labels": "targeted_recapture",
    "calibrated_rgb": "targeted_recapture",
    "calibrated_depth": "targeted_recapture",
    "calibrated_lidar": "targeted_recapture",
    "calibrated_imu": "sensor_calibration",
    "sensor_calibration": "sensor_calibration",
    "sensor_timing": "sensor_calibration",
    "robot_controller_calibration": "sensor_calibration",
    "articulation_model": "articulation_measurement",
    "articulation_actuation": "articulation_measurement",
    "material_parameters": "material_identification",
    "friction_contact": "material_identification",
    "mass_inertia": "material_identification",
    "physical_specimens": "material_identification",
    "initial_material_state": "targeted_recapture",
    "dynamic_object_tracks": "targeted_recapture",
    "force_tactile": "force_tactile_collection",
    "real_demonstrations": "physical_execution",
    "physical_outcomes": "physical_execution",
    "gaussian_splat_appearance": "targeted_recapture",
    "appearance_mesh": "targeted_recapture",
}
